# Generated by Django 5.1.4 on 2025-01-10 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfProducts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_product', to='api.typeofproducts')),
            ],
        ),
    ]
